name: Build and Release for Linux and macOS

on:
  push:
    branches:
      - main  # или другая ветка, при пуше в которую будет триггериться workflow

jobs:
  # Workflow для сборки и релиза на macOS
  build-macos:
    runs-on: macos-latest
    permissions: write-all # Заданию предоставляются права на запись во все ресурсы GitHub
    steps:
      # Чекаут кода
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Установка зависимостей для macOS
      - name: Install dependencies
        run: brew update && brew install boost

      # Генерация сборочных файлов
      - name: Configure project
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}

      # Компиляция проекта
      - name: Build project
        run: cmake --build .

      # Запуск тестов (если у вас их нет, можно убрать этот шаг)
      - name: Run tests
        run: cmake --build . --target test || echo "No tests to run"

      # Создание пакета для macOS (убедитесь, что у вас настроен CPack)
      - name: Package for macOS
        run: cmake --build . --target package

      # Проверка на существование тега перед созданием релиза
      - name: Check if tag exists
        run: |
          if git rev-parse "refs/tags/v${{ github.run_number }}-macos" >/dev/null 2>&1; then
            echo "Tag exists for macOS. Exiting..."
            exit 0
          fi

      # Создание релиза для macOS
      - name: Create Release for macOS
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-macos
          release_name: Release ${{ github.run_number }} for macOS
          draft: false
          prerelease: false

      # Загрузка пакета в релиз для macOS (уберите эту часть, если пакет не создается)
      - name: Upload macOS Release Asset
        id: upload_release_asset_macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: ./helloworld-0.0.${{ github.run_number }}-macOS.pkg  # Убедитесь, что этот файл создается!
          asset_name: helloworld-0.0.${{ github.run_number }}-macOS.pkg
          asset_content_type: application/octet-stream

  # Workflow для сборки и релиза на Linux (удалены шаги для создания пакета)
  build-linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Чекаут кода
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Установка зависимостей для Linux
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libboost-test-dev

      # Генерация сборочных файлов
      - name: Configure project
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}

      # Компиляция проекта
      - name: Build project
        run: cmake --build .

      # Запуск тестов (если у вас их нет, можно убрать этот шаг)
      - name: Run tests
        run: cmake --build . --target test || echo "No tests to run"

      # Проверка на существование тега перед созданием релиза (удалены шаги для создания пакета)
      - name: Check if tag exists
        run: |
          if git rev-parse "refs/tags/v${{ github.run_number }}-linux" >/dev/null 2>&1; then
            echo "Tag exists for Linux. Exiting..."
            exit 0
          fi


      # Создание релиза для Linux (удалены шаги для загрузки пакета)
      - name: Create Release for Linux
        id: create_release_linux
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-linux
          release_name: Release ${{ github.run_number }} for Linux
          draft: false
          prerelease: false
