name: C++ CI

on: 
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - name: Run Tests
        run: |
          ctest --output-on-failure || exit 1
      - run: cmake --build . --target package
      - name: Create Release (Ubuntu)
        id: create_release_ubuntu
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }} (Ubuntu)
          draft: false
          prerelease: false
      - name: Upload Release Asset (Ubuntu)
        id: upload-release-asset-ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_ubuntu.outputs.upload_url }}
          asset_path: ./coollab2-0.0.${{ github.run_number }}-Linux.deb
          asset_name: coollab2-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

  build_macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: brew install boost
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      - run: cmake --build .
      - name: Run Tests
        run: |
          ctest --output-on-failure || exit 1
      
      # Создаем пакет перед созданием релиза
      - run: cmake --build . --target package

      # Проверяем, существует ли созданный архив перед загрузкой 
      - name: Check if ZIP exists for MacOS
        run: |
          if [ ! -f "./coollab2-0.0.${{ github.run_number }}-Darwin.zip" ]; then 
            echo "Error: ZIP file does not exist!" && exit 1; 
          fi

      # Создаем релиз для MacOS
      - name: Create Release (MacOS)
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }} 
          release_name: Release ${{ github.run_number }} (MacOS)
          draft: false 
          prerelease: false

      # Загружаем релизный ассет для MacOS
      - name: Upload Release Asset (MacOS)
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: ./coollab2-0.0.${{ github.run_number }}-Darwin.zip 
          asset_name: coollab2-0.0.${{ github.run_number }}-Darwin.zip 
          asset_content_type: application/zip 