name: Build and Release for Linux and macOS

on:
  push:
    branches:
      - main
      - feature/github_actions
    tags:
      - "v*.*.*"  # Trigger on version tags (e.g., v1.0.0)

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - run: sudo apt-get update && sudo apt-get install libboost-test-dev -y
      
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      
      - run: cmake --build .
      
      - name: Run Tests
        run: |
          ctest --output-on-failure || exit 1
      
      - run: cmake --build . --target package
      
      - name: Create or Update Release (Ubuntu)
        id: create_release_ubuntu
        uses: ncipollo/release-action@v1
        with:
          tag_name: v${{ github.run_number }}  # Use the run number as the tag
          release_name: Release ${{ github.run_number }} (Ubuntu)
          allowUpdates: true  # Allow updating existing releases
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload Release Asset (Ubuntu)
        id: upload-release-asset-ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_ubuntu.outputs.upload_url }}
          asset_path: ./coollab2-0.0.${{ github.run_number }}-Linux.deb
          asset_name: coollab2-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package

  build_macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - run: brew install boost
      
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      
      - run: cmake --build .
      
      - name: Run Tests
        run: |
          ctest --output-on-failure || exit 1
      
      - run: cmake --build . --target package
      
      - name: Create or Update Release (MacOS)
        id: create_release_macos
        uses: ncipollo/release-action@v1
        with:
          tag_name: v${{ github