name: Build and Release for Linux and macOS

on:
  push:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: brew update && brew install boost

      - name: Configure project
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}

      - name: Build project
        run: cmake --build .

      - name: Run tests
        run: cmake --build . --target test || echo "No tests to run"

      - name: Check if tag exists
        id: check_tag_macos
        run: |
          if git rev-parse "refs/tags/v${{ github.run_number }}-macos" >/dev/null 2>&1; then
            echo "Tag exists for macOS. Exiting..."
            echo "tag_exists=true" >> $GITHUB_ENV 
            exit 0
          else
            echo "tag_exists=false" >> $GITHUB_ENV 
          fi

      - name: Create Release for macOS
        if: env.tag_exists != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-macos
          release_name: Release ${{ github.run_number }} for macOS
          draft: false
          prerelease: false

  build-linux:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libboost-test-dev

      - name: Configure project
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}

      - name: Build project
        run: cmake --build .

      - name: Run tests
        run: cmake --build . --target test || echo "No tests to run"

      - name: Check if tag exists for Linux
        id: check_tag_linux
        run: |
          if git rev-parse "refs/tags/v${{ github.run_number }}-linux" >/dev/null 2>&1; then
            echo "Tag exists for Linux. Exiting..."
            echo "tag_exists=true" >> $GITHUB_ENV 
            exit 0 
          else 
            echo "tag_exists=false" >> $GITHUB_ENV 
          fi

      - name: Create Release for Linux 
        if: env.tag_exists != 'true'
        uses: actions/create-release@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}-linux 
          release_name: Release ${{ github.run_number }} for Linux 
          draft: false 
          prerelease: false 
