name: 'C++ CI'

on: 
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build_windows:
    runs-on: windows-latest 
    permissions: write-all 
    steps:
      - uses: actions/checkout@v3  
        with:
          submodules: true
      
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }} 
      
      - run: cmake --build . 
      
      - run: cmake --build . --target package 
      
      - name: List files before creating release
        run: dir
      
      # Creates release without checking if the tag exists
      - name: Create Release (Windows)
        id: create_release_windows
        uses: ncipollo/release-action@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          tag_name: v${{ github.run_number }}-${{ github.sha }}  # Use unique tag names
          release_name: Release v${{ github.run_number }} (Windows)
          allowUpdates: true  # Allow updating existing releases
          draft: false 
          prerelease: false 
      
      - name: Upload Release Asset (Windows)
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_windows.outputs.upload_url }}
          asset_path: ./laba3-0.0.${{ github.run_number }}-win64.zip  
          asset_name: laba3-0.0.${{ github.run_number }}-win64.zip
          asset_content_type: application/zip
  
  build_ubuntu:
    runs-on: ubuntu-latest  
    permissions: write-all  
    steps:
      - uses: actions/checkout@v3  
        with:
          submodules: true
      
      - run: cmake . -DPATCH_VERSION=${{ github.run_number }}  
      
      - run: cmake --build .  
      
      - run: cmake --build . --target package  
      
      # Creates release without checking if the tag exists for Ubuntu
      - name: Create Release (Ubuntu)
        id: create_release_ubuntu
        uses: ncipollo/release-action@v1  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        with:
          tag_name: v${{ github.run_number }}-${{ github.sha }}  # Use unique tag names
          release_name: Release v${{ github.run_number }} (Ubuntu)
          allowUpdates: true  # Allow updating existing releases
          draft: false  
          prerelease: false 
      
      # Uploads the release asset for Ubuntu
      - name: Upload Release Asset (Ubuntu)
        id: upload-release-asset-ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_ubuntu.outputs.upload_url }}
          asset_path: ./laba3-0.0.${{ github.run_number }}-Linux.deb  
          asset_name: laba3-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
